const $album_image = [
	'1 Basic.png',
	'2 Garuda Component.png',
	'3 Ajax.png',
	'4 Single Data.png',
	'5 Multiple Data.png',
	'6 Input Focus Value.png',
	'7 Button Event.png',
	'8 Preview Image.png',
	'9 Load Image From URL.png',
	'10 Mouse Scroll.png',
	'11 HTML Keyup Keydown.png',
	'12 Custom Console Log.png',
	'13 Cookie.png',
	'14 Copy Select.png',
	'15 Date Time.png',
	'16 Day Name Month Name Array.png',
	'17 Import Javascript File.png',
	'18 Insert Duplicate Find.png',
	'19 Check Array.png',
	'20 Check Email.png',
	'21 Check Function.png',
	'22 Key Code.png',
	'23 Money Format.png',
	'24 Canvas.png',
	'25 Custom Print.png',
	'26 Query Selector.png',
	'27 Random String Integer.png',
	'28 Setting Input.png',
	'29 Storage.png',
	'30 Title.png',
	'31 Convert Array to JSON.png',
	'32 Get URL Check URL.png',
	'33 Get Type Of Object.png',
	'34 Animate FadeIn FadeOut.png',
	'35 Garuda-Import-SingleData.png',
	'36 Garuda-Import-Multiple-Data.png',
	'37 Garuda-Route.png',
	'38 Garuda-Template.png'
]
